package HelloApp;


/**
* HelloApp/HelloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public abstract class HelloPOA extends org.omg.PortableServer.Servant
 implements HelloApp.HelloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("viewMenu", new java.lang.Integer (0));
    _methods.put ("placeOrder", new java.lang.Integer (1));
    _methods.put ("checkOrderStatus", new java.lang.Integer (2));
    _methods.put ("viewAllOrders", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloApp/Hello/viewMenu
       {
         String $result = null;
         $result = this.viewMenu ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HelloApp/Hello/placeOrder
       {
         try {
           String username = in.read_string ();
           int chickenQty = in.read_long ();
           int colaQty = in.read_long ();
           String $result = null;
           $result = this.placeOrder (username, chickenQty, colaQty);
           out = $rh.createReply();
           out.write_string ($result);
         } catch (HelloApp.InvalidOrder $ex) {
           out = $rh.createExceptionReply ();
           HelloApp.InvalidOrderHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // HelloApp/Hello/checkOrderStatus
       {
         try {
           String username = in.read_string ();
           HelloApp.Order $result = null;
           $result = this.checkOrderStatus (username);
           out = $rh.createReply();
           HelloApp.OrderHelper.write (out, $result);
         } catch (HelloApp.OrderNotFound $ex) {
           out = $rh.createExceptionReply ();
           HelloApp.OrderNotFoundHelper.write (out, $ex);
         }
         break;
       }

       case 3:  // HelloApp/Hello/viewAllOrders
       {
         HelloApp.Order $result[] = null;
         $result = this.viewAllOrders ();
         out = $rh.createReply();
         HelloApp.OrderListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloApp/Hello:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hello _this() 
  {
    return HelloHelper.narrow(
    super._this_object());
  }

  public Hello _this(org.omg.CORBA.ORB orb) 
  {
    return HelloHelper.narrow(
    super._this_object(orb));
  }


} // class HelloPOA
