package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public interface HelloOperations 
{
  String viewMenu ();
  String placeOrder (String username, int chickenQty, int colaQty) throws HelloApp.InvalidOrder;
  HelloApp.Order checkOrderStatus (String username) throws HelloApp.OrderNotFound;
  HelloApp.Order[] viewAllOrders ();
} // interface HelloOperations
