package HelloApp;

/**
* HelloApp/InvalidOrderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class InvalidOrderHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.InvalidOrder value = null;

  public InvalidOrderHolder ()
  {
  }

  public InvalidOrderHolder (HelloApp.InvalidOrder initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.InvalidOrderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.InvalidOrderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.InvalidOrderHelper.type ();
  }

}
