package HelloApp;


/**
* HelloApp/InvalidOrder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class InvalidOrder extends org.omg.CORBA.UserException
{
  public String message = null;

  public InvalidOrder ()
  {
    super(InvalidOrderHelper.id());
  } // ctor

  public InvalidOrder (String _message)
  {
    super(InvalidOrderHelper.id());
    message = _message;
  } // ctor


  public InvalidOrder (String $reason, String _message)
  {
    super(InvalidOrderHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class InvalidOrder
