package HelloApp;


/**
* HelloApp/Order.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class Order implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public int chickenQty = (int)0;
  public int colaQty = (int)0;
  public int totalPrice = (int)0;

  public Order ()
  {
  } // ctor

  public Order (String _username, int _chickenQty, int _colaQty, int _totalPrice)
  {
    username = _username;
    chickenQty = _chickenQty;
    colaQty = _colaQty;
    totalPrice = _totalPrice;
  } // ctor

} // class Order
