package HelloApp;


/**
* HelloApp/OrderNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class OrderNotFound extends org.omg.CORBA.UserException
{
  public String message = null;

  public OrderNotFound ()
  {
    super(OrderNotFoundHelper.id());
  } // ctor

  public OrderNotFound (String _message)
  {
    super(OrderNotFoundHelper.id());
    message = _message;
  } // ctor


  public OrderNotFound (String $reason, String _message)
  {
    super(OrderNotFoundHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class OrderNotFound
