package HelloApp;

/**
* HelloApp/OrderNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class OrderNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.OrderNotFound value = null;

  public OrderNotFoundHolder ()
  {
  }

  public OrderNotFoundHolder (HelloApp.OrderNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.OrderNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.OrderNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.OrderNotFoundHelper.type ();
  }

}
