package HelloApp;

/**
* HelloApp/OrderHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 22, 2026 4:22:18 PM CDT
*/

public final class OrderHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.Order value = null;

  public OrderHolder ()
  {
  }

  public OrderHolder (HelloApp.Order initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.OrderHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.OrderHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.OrderHelper.type ();
  }

}
