/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define DATE_PROG ((rpc_uint)0x31234567)
#define DATE_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define DATE ((rpc_uint)1)
extern "C" char ** date_1(long *, CLIENT *);
extern "C" char ** date_1_svc(long *, struct svc_req *);

#elif __STDC__
#define DATE ((rpc_uint)1)
extern  char ** date_1(long *, CLIENT *);
extern  char ** date_1_svc(long *, struct svc_req *);

#else /* Old Style C */
#define DATE ((rpc_uint)1)
extern  char ** date_1();
extern  char ** date_1_svc();
#endif /* Old Style C */

#endif /* !_DATE_H_RPCGEN */
