/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

char **
date_1(argp, rqstp)
	long *argp;
	struct svc_req *rqstp;
{

	static char * result;

	/*
	 * insert server code here
	 */

	return(&result);
}
